# Generated by Django 4.1 on 2022-08-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0003_alter_variacao_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="tipo",
            field=models.CharField(
                choices=[("V", "Variável"), ("S", "Simples")],
                default="V",
                max_length=1,
                verbose_name="Tipo",
            ),
        ),
    ]
