# Generated by Django 4.1 on 2022-08-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0004_alter_produto_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="slug",
            field=models.SlugField(null=True, unique=True, verbose_name="Slug"),
        ),
    ]
