# Generated by Django 4.1 on 2022-08-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0005_alter_produto_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="Slug"
            ),
        ),
    ]
