# Generated by Django 4.1 on 2022-08-18 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0006_alter_produto_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="descricao_curta",
            field=models.TextField(max_length=255, verbose_name="Descrição Curta"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="produto_imagens/%Y/%m/",
                verbose_name="Imagem",
            ),
        ),
        migrations.AlterField(
            model_name="variacao",
            name="estoque",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="variacao",
            name="nome",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="variacao", name="preco", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="variacao",
            name="preco_promocional",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="variacao",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="produto.produto"
            ),
        ),
    ]
