# Generated by Django 4.1 on 2022-08-10 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.FloatField(default=0, verbose_name="Total")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Aprovado"),
                            ("C", "Criado"),
                            ("R", "Reprovado"),
                            ("P", "Pendente"),
                            ("E", "Enviado"),
                            ("F", "Finalizado"),
                        ],
                        default="C",
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produto", models.CharField(max_length=255, verbose_name="Produto")),
                (
                    "produto_id",
                    models.PositiveIntegerField(verbose_name="ID do Produto"),
                ),
                ("variacao", models.CharField(max_length=255, verbose_name="Variação")),
                (
                    "variacao_id",
                    models.PositiveIntegerField(verbose_name="ID da Variação"),
                ),
                ("preco", models.FloatField(verbose_name="Preço")),
                (
                    "preco_promocional",
                    models.FloatField(default=0, verbose_name="Preço Promocional"),
                ),
                ("quantidade", models.FloatField(verbose_name="Quantidade")),
                ("imagem", models.CharField(max_length=255)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pedido.pedido",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens do Pedido",
            },
        ),
    ]
