# Generated by Django 4.1 on 2022-09-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="qtd_total",
            field=models.PositiveBigIntegerField(default=0, verbose_name="Qtd Total"),
            preserve_default=False,
        ),
    ]
